# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 16 is convenient
# when copying and pasting from another recipe, but not really needed.

package:
  name: "rest_regression"
  version: v2025.02

source:
  - git: https://gitee.com/restgroup/rest_regression.git
    # git_rev: af3223852d5c240c004ef200c5d1fb0270df2267
    tag: v2025.02
    target_directory: rest_regression

build:
  number: 2
  # Uncomment the following line if the package is pure Python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python for more details.
  # noarch: python
  # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Add the line "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit to Windows.
  # More info about selectors can be found in the conda-build docs:
  # https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors
  script:
    content: |
      cd rest_regression
      cargo install --path . --profile release --root ${PREFIX}

requirements:
  build:
    - ${{ compiler('rust') }}
    # - libclang
    - sysroot_linux-64 ==2.17
  # host:
  # run:

about:
  homepage: https://gitee.com/restgroup/rest_regression
  # summary: 'Rust-based Electronic-Structure Toolkit (REST), aiming at an efficient computational platform for state-of-the-art DFT and WFT methods.'
  # description: |
  #   Rust-based Electronic-Structure Toolkit (REST),
  #   aiming at an efficient computational platform for state-of-the-art DFT and WFT methods.
#   # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
#   # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
#   # See https://spdx.org/licenses/
# license: GPL-2.0-only
#   # The license_family, i.e. "BSD" if license is "BSD-3-Clause".
#   # Optional
#   license_family: MIT
#   # It is required to include a license file in the package,
#   # (even if the license doesn't require it) using the license_file entry.
#   # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
#   # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
#   license_file: LICENSE.txt
#   # The doc_url and dev_url are optional.
#   doc_url: https://simplejson.readthedocs.io/
#   dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - jeanwsr
