name: checkout-cache-setup-conda
description: Checkout and setup conda environment
runs:
  using: composite
  steps:
    - name: Cache conda
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('env_rattler.yaml') }}
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: build-env
        python-version: 3.11
        environment-file: env_rattler.yaml
        # use-mamba: true
