# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 16 is convenient
# when copying and pasting from another recipe, but not really needed.

package:
  name: "rest"
  version: "2025.02.1"

source:
  #url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  # url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  # and otherwise fall back to archive:
  # url: https://https://gitee.com/canarias/rest/archive/v{{ version }}.tar.gz
  #sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge`
  - git: https://gitee.com/restgroup/rest_workspace.git
    tag: v2025.02
    # rev: master
  - git: https://gitee.com/restgroup/rest.git
    #tag: v2025.01
    rev: 98bdcf9fb574d4a522f9731e86b1ada269b74b0e
    target_directory: rest
  - git: https://gitee.com/restgroup/rest_tensors.git
    tag: v2025.02
    # rev: master
    target_directory: rest_tensors
  - git: https://gitee.com/restgroup/rest_libcint.git
    #tag: v2025.01
    rev: ae4f08951ec1746fdc01551c5ae2db1da5c2bd69
    target_directory: rest_libcint
  - git: https://gitee.com/restgroup/rest_regression.git
    tag: v2025.02
    # rev: af3223852d5c240c004ef200c5d1fb0270df2267
    target_directory: rest_regression

build:
  number: 5
  files:
    exclude:
      - "**/__pycache__"
      - "**/test-files"
  script:
    env:
      REST_HOME: ${SRC_DIR}
      REST_EXT_DIR: "${SRC_DIR}/rest_deps/lib"
      HDF5_DIR: "${BUILD_PREFIX}"
    content: |
      set -ex
      cd rest
      mkdir ../rest_deps
      mkdir ../rest_deps/lib
      cp ${BUILD_PREFIX}/lib/*.so ../rest_deps/lib/
      cp ${BUILD_PREFIX}/lib/python${PY_VER}/site-packages/mokit/lib/librest2fch.so ../rest_deps/lib/
      export LIBCLANG_PATH="$BUILD_PREFIX/lib"
      # export GCC_INCLUDE="${BUILD_PREFIX}/lib/gcc/x86_64-conda-linux-gnu/15.2.0/include/"
      # export CFLAGS="--sysroot=${CONDA_BUILD_SYSROOT} -I${GCC_INCLUDE} -I${CONDA_BUILD_SYSROOT}/usr/include"
      # export CXXFLAGS="--sysroot=${CONDA_BUILD_SYSROOT} -I${GCC_INCLUDE} -I${CONDA_BUILD_SYSROOT}/usr/include"
      # export LDFLAGS="--sysroot=${CONDA_BUILD_SYSROOT}"
      # export RUSTFLAGS="--verbose -C link-arg=--sysroot=${CONDA_BUILD_SYSROOT} -C link-arg=-Wl,--dynamic-linker=${CONDA_BUILD_SYSROOT}/lib64/ld-linux-x86-64.so.2 -C link-arg=--verbose -C link-arg=-Wl,--verbose"
      # export BINDGEN_EXTRA_CLANG_ARGS="--sysroot=$CONDA_BUILD_SYSROOT -I${GCC_INCLUDE} -I${CONDA_BUILD_SYSROOT}/usr/include"
      # echo $LDFLAGS
      # ls ${CONDA_BUILD_SYSROOT}/usr/lib
      # cargo build --release --verbose --target=x86_64-unknown-linux-gnu
      # export RUSTFLAGS="-C link-arg=--verbose -C link-arg=-Wl,--verbose"
      # export LD_LIBRARY_PATH="${CONDA_BUILD_SYSROOT}/usr/lib:${LD_LIBRARY_PATH}"
      # export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="clang"
      # export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-C link-arg=-fuse-ld=$CONDA_PREFIX/bin/mold"
      cargo install --path . --profile release --root ${PREFIX}
      mkdir -p ${PREFIX}/share/rest/
      cp -r ./basis-set-pool ${PREFIX}/share/rest/ 
      cp ../rest_deps/lib/librestmatr.so ${PREFIX}/lib/
      cp ../rest_deps/lib/librest2fch.so ${PREFIX}/lib/
      # todo: remove the manual copy

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx', 'fortran', among others
    - ${{ compiler('c') }}
    #- {{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - ${{ compiler('rust') }}
    - libclang
    - hdf5
    - libcint
    - openblas * openmp*
    - python
    - libxc-c
    - openmpi 4.*
    - mokit
    - geometric
    - simple-dftd3
    - dftd4
    - sysroot_linux-64 ==2.17
    # - clang
    # - lld
  host:
    - hdf5
    - libcint
    - openblas * openmp*
    - python
    - libxc-c
    - openmpi 4.*
    - mokit
    - geometric
    - simple-dftd3
    - dftd4
  run:
    - hdf5
    - libcint
    - openblas * openmp*
    - python
    - libxc-c
    - openmpi 4.*
    - mokit
    - geometric
    - simple-dftd3
    - dftd4

tests:
  - script: run_tests.sh
    requirements:
      run:
        # - {{ compiler('rust') }}
        - restgroup::rest_regression
    files:
      source:
        # - rest/basis-set-pool
        - rest_regression
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  # imports:
  #   - simplejson
  #   - simplejson.tests
  # For python packages, it is useful to run pip check. However, sometimes the
  # metadata used by pip is out of date. Thus this section is optional if it is
  # failing.
  # requires:
  #   - pip

about:
  homepage: https://gitee.com/restgroup/rest
  summary: "Rust-based Electronic-Structure Toolkit (REST), aiming at an efficient computational platform for state-of-the-art DFT and WFT methods."
  description: |
    Rust-based Electronic-Structure Toolkit (REST), 
    aiming at an efficient computational platform for state-of-the-art DFT and WFT methods.
  #   # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  #   # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  #   # See https://spdx.org/licenses/
  license: GPL-2.0-only
#   # The license_family, i.e. "BSD" if license is "BSD-3-Clause".
#   # Optional
#   license_family: MIT
#   # It is required to include a license file in the package,
#   # (even if the license doesn't require it) using the license_file entry.
#   # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
#   # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
#   license_file: LICENSE.txt
#   # The doc_url and dev_url are optional.
#   doc_url: https://simplejson.readthedocs.io/
#   dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - jeanwsr
