# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 16 is convenient
# when copying and pasting from another recipe, but not really needed.

package:
  name: "rest-util"
  version: "2025.02"

source:
  #url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  # url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  # and otherwise fall back to archive:
  # url: https://https://gitee.com/canarias/rest/archive/v{{ version }}.tar.gz
  #sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge`
  - git: https://gitee.com/restgroup/rest_workspace.git
    tag: v2025.02

build:
  number: 1
  # noarch: python
  script:
    content: |
      set -ex
      mkdir -p ${PREFIX}/bin
      cp utilities/*.py ${PREFIX}/bin

requirements:
  run:
    - python 3.11.*
    - matplotlib
    - numpy
    - scipy

# about:
#   homepage: https://gitee.com/restgroup/rest
#   summary: "Rust-based Electronic-Structure Toolkit (REST), aiming at an efficient computational platform for state-of-the-art DFT and WFT methods."
#   description: |
#     Rust-based Electronic-Structure Toolkit (REST),
#     aiming at an efficient computational platform for state-of-the-art DFT and WFT methods.
#   #   # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
#   #   # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
#   #   # See https://spdx.org/licenses/
#   license: GPL-2.0-only
#   # The license_family, i.e. "BSD" if license is "BSD-3-Clause".
#   # Optional
#   license_family: MIT
#   # It is required to include a license file in the package,
#   # (even if the license doesn't require it) using the license_file entry.
#   # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
#   # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
#   license_file: LICENSE.txt
#   # The doc_url and dev_url are optional.
#   doc_url: https://simplejson.readthedocs.io/
#   dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - jeanwsr
